### PR TITLE
Upgrade pytest to version 7.2.0

### PR DESCRIPTION
**Pull request by chrisnovakovic**
pytest 5.4.3 isn't compatible with Python 3.10 and newer. Python 3.10 support was officially added in pytest 6.2.5, while Python 3.11 isn't officially supported yet but appears to work correctly as of pytest 7.2.0. Upgrade to version 7.2.0 and pack its new dependencies into the pytest bootstrap pex.

This also requires upgrading coverage from 5.5 to 6.5.0, which drops support for Python 3.5 and 3.6. (Both versions are now end-of-life.)

Fixes https://github.com/thought-machine/please/issues/2570.

### CODE REVIEW

**Comment by chrisnovakovic** [comment]
This also causes `//test:python2_coverage_test` to fail, since coverage 5.0.0 drops support for Python 2. @samwestmoreland is this a problem?

**Comment by peterebden** [comment]
We did have some users on Python 2 fairly recently, but they weren't using the plugin AFAIK.

I think we have to drop it at this point - it's more important we support 3.10 and 3.11 than the EOL versions. Although probably that should constitute a major version of the plugin?

**Comment by samwestmoreland** [comment]
Nice one, thanks, Chris! Yeah, I think more users will be happy that we're supporting pythons 3.10 and 3.11 than will be disappointed that we're dropping older versions. But regardless, I agree with Pebers - more important to support 3.10 and 3.11 and to stay up-to-date in general, especially in this instance given the performance gains.

The only question is over the release... We've been developing on the v1 branch and tagging the v1 releases from there. I think the thing to do is to merge the v1 branch back into master, and tag v2 on the master branch. Does anyone have any thoughts/objections?

**Comment by chrisnovakovic** [comment]
Completely missed the activity on the `v1` branch, sorry. I can rebase this on that branch if you like.

**Comment by samwestmoreland** [comment]
I'll copy your other fix over to v1 here: https://github.com/please-build/python-rules/pull/85

**Comment by chrisnovakovic** [comment]
This is already on the `v1` branch, which has been merged back into master now.

**Pull request closed without merging**
