### PR TITLE
Use remote pex tool on host repo and guarantee hash correctness

### PR DESCRIPTION
**Pull request by tiagovtristao**
Re-enable work done in https://github.com/please-build/python-rules/pull/44 that had been reverted.

### CODE REVIEW

**Review by samwestmoreland — APPROVED** [review]
Nice!

**Comment by Tatskaari** [comment]
I've put a load of thought into this now and this just seems like a symptom of a bigger problem. We also have an issue where we create a new version of the tool each time we do a release. This really sucks because it invalidates all the caches after each Please release. 

I think we probably want to create releases like `pex-tool-v1.0.0` so we can version and release the tools independently of the plugin.

**Comment by tiagovtristao** [comment]
> 

Yeah, not super happy with this approach myself. I think we were just exploring some ground. Ideally, we would have a better idiomatic way of achieving the same thing.

**Comment by tiagovtristao** [comment]
> I've put a load of thought into this now and this just seems like a symptom of a bigger problem. We also have an issue where we create a new version of the tool each time we do a release. This really sucks because it invalidates all the caches after each plugin release.
> 
> I think we probably want to create releases like `pex-tool-v1.0.0` so we can version and release the tools independently of the plugin.

Yeah, not super happy with this approach myself. I think we were just exploring some ground. Ideally, we would have a better idiomatic way of achieving the same thing.

**Comment by tiagovtristao** [comment]
Too much magic going on here, and the approach of splitting the releases between build defs and the tools is a better approach.

**Pull request closed without merging**
