### PR TITLE
Set up Python versions as a matrix

### PR DESCRIPTION
**Pull request by peterebden**
Seems to be failing at present; unsure exactly why although a likely candidate is that 3.6 isn't supported any more.

Anyway, I think we need to test this on as many versions as possible; we want compatibility with older ones, but we also see things failing on the newer versions (e.g. I've seen pytest not working on 3.10+).

### CODE REVIEW

**Review by samwestmoreland — APPROVED** [review]

**Comment by samwestmoreland** [comment]
I think we might want this on the v1 branch too. Think the plan is to eventually tag v2 on this master branch and then do away with the v1 branch, but in the meantime, we need to maintain both annoyingly

**Comment by peterebden** [comment]
Cool done it in #95

**Comment by peterebden** [comment]
Ergh seems to be failing on compiling a bunch of the stuff in third_party? Are we expecting that? Bit suspicious given the v1 branch doesn't seem to be doing that.

**Comment by samwestmoreland** [comment]
Think we can delete that python2 coverage test that's failing (i.e. drop support for python2). We did it on the v1 branch [here](https://github.com/please-build/python-rules/pull/89)

**Pull request merged**
